### ISSUE TITLE
Docs Request: Example Project

### ISSUE THREAD

**Issue by svallory** [ash-project/spark#109]
hey guys!

Spark looks amazing, and I wanted to try it out for creating a simple DSL. I understand (I think), Spark's mental model and main classes, but I'm not familiar with Elixir yet. Actually, Spark is what made me wanna learn elixir.

So, is there an example project of an Elixir/Spark based program that can like processes a Spark DSL and outputs a JSON object or whatever?

If there's a tiny transformer example in the mix that's even better, but that shouldn't be hard to add

**Comment by svallory** [comment]
Thanks for the info, @zachdaniel!

I'm going to continue here since the content in discord can't be found via web search. What I'm looking for is "How to use Spark **without** Ash". All the instructions I found were about how to write DSLs, inspect, and manipulate them. I was even aware of the `.Info` module.

What I did not find was how to use Spark standalone to, for example, create a binary that takes a DSL file and processes it into whatever (e.g. JSON).

If you don't mind, a simple script on what it takes to parse a DSL file using Spark would suffice. I only need the bootstrapping part. The rest is either already documented or just plain Elixir.

**Comment by zachdaniel** [comment]
When you say "process a DSL file" are you expecting spark to parse a file? Spark generates Elixir code. You can see some examples of how it's used in our tests. I'm not sure if you're expecting spark to do/be something that it doesn't/isnt. What you see in the tests is the gist of what spark does.

I.e you define a DSL with `use Spark.Dsl`, plus some extensions, and then other people can `use YourDsl` in their Elixir code.

**Comment by zachdaniel** [comment]
https://github.com/ash-project/spark/blob/v2.2.30/test/support/contact/contact.ex this file defines a DSL. With that definition people can define modules that use that DSL, and each module that does can be interrogated with the info module.

I think the best thing here would be for you to say more about what specifically(not in the abstract) you are trying to build.

**Comment by svallory** [comment]
> When you say "process a DSL file" are you expecting spark to parse a file?

hehehe sorry. I was using the term "parse" very loosely. I understand Spark uses Elixir macros under the hood.

My goal is to create a DSL that can convert this code...

```elixir
app "My Application" do
  context :Public do
    screen :Login, modal: true do
      preconditions [
        "User is not logged in"
      ]

      form :Login /login do
        @method :post
        
        image :SiteLogo /logo.png

        fields do
          Username @required "Enter Username"
          Password @required "Enter Password"
          Toggle "Remember me"
        end

        actions do
          |> Submit "Login"
          |> Cancel
        end

        > "Forgot Password"
      end
    end
  end
end
```

into an object like this:

```yaml
app:
  name: My Application
  contexts:
    Public:
      screens:
        Login:
          modal: true
          preconditions:
            - User is not logged in
          
          children:
            - concept: Image
              id: SiteLogo
              url: /logo.png
              
            - concept: Form
              name: Login
              path: /login
              method: post
              
              fields:
                - concept: Username
                  name: Enter Username
                  required: true
                  
                - concept: Password
                  name: Enter Password
                  required: true
                  
                - concept: Toggle
                  name: Remember me
                  
              actions:
                Submit:
                  concept: Submit # expands on Action
                  name: Login
                  
                Cancel:
                  concept: Cancel # expands on Action
                  
            - concept: Link
              name: Forgot Password
```

I have an implementation of this using, believe it or not, Pug! Using a set Pug mixins, that code initially generates a visual documentation of the app's screens. The dev team then creates another set of mixins that converts that code into components.

I'm looking into replacing Pug with Elixir + Spark. I'll I need the pair to do though is convert UISL (that's the DSL name) into yaml or json.
